use std::str::FromStr;
use std::time::Duration;
use crate::ast::{Command as AstCommand};

grammar;

pub Command: AstCommand = {
    "scan" <n:Num> => AstCommand::Scan(Duration::from_secs(n)),

    "exit" => AstCommand::Exit,
    "quit" => AstCommand::Exit,
    "help" => AstCommand::Help,
    "list" => AstCommand::List,
    "test" <n:Num> => AstCommand::Test(n),
}

Num: u64 = <s:r"[0-9]+"> => u64::from_str(s).unwrap();